clean:
	rm -rf *.md *.html *.pdf cache/ figure/

%.html: %.Rmd
	./make_slides $(basename $(@))

all: clean 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15



1: 1_nimble_background.html
10: 10_operating_model.html
13: 13_exercises2.html
4: 4_run_mcmc.html
7: 7_user_dist.html
0: overview.html
11: 11_model_structure.html
14: 14_nimbleFunction_smc.html
2: 2_bugs_language.html
5: 5_customizing_mcmc.html
8: 8_exercises.html
12: 12_user_sampler.html
15: 15_wrapup.html
3: 3_build_model.html
6: 6_nimble_bugs.html
9: 9_basic_nimbleFunction.html
